---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: dbinstance-pgexporter-query
data:
  queries.yaml: |
{{ .Values.exporter.postgres.query | indent 4 }}