version: "3.9"
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test1234"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "test1234"
  sqladmin:
    build: ./mock
    ports:
      - "8080:8080"
    environment:
      LOG_LEVEL: "DEBUG"